# Generated by Django 4.2.11 on 2024-06-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isyv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
