# Generated by Django 5.0.6 on 2024-06-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isyv', '0002_rename_user_comment_author_rename_user_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_start', models.TextField(max_length=10, null=True)),
                ('cut_end', models.TextField(max_length=10, null=True)),
                ('pitch', models.TextField(max_length=10, null=True)),
                ('sound_file', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
