# Generated by Django 5.0.6 on 2024-06-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isyv', '0003_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='title',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
