# Generated by Django 5.0.6 on 2024-06-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isyv', '0004_fileupload_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='cut_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='cut_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='pitch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='sound_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
