# Generated by Django 5.0.6 on 2024-06-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isyv', '0005_alter_fileupload_cut_end_alter_fileupload_cut_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceLeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
