# Generated by Django 5.0.6 on 2024-06-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isyv', '0006_voiceleaning'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoiceLeaning',
            new_name='VoiceLearning',
        ),
    ]
