# Generated by Django 5.0.6 on 2024-06-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isyv', '0007_rename_voiceleaning_voicelearning'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(blank=True, null=True, upload_to='')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
